<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'system\\Controllers\\requestlogs' => 'modules\\system\\controllers\\requestlogs.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'sergeikuznetsov\\juniortestplugin\\Plugin' => 'plugins\\sergeikuznetsov\\juniortestplugin\\Plugin.php',
  'system\\Controllers\\eventlogs' => 'modules\\system\\controllers\\eventlogs.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
  'cms\\Controllers\\themes' => 'modules\\cms\\controllers\\themes.php',
  'sergeikuznetsov\\juniortestplugin\\Controllers\\products' => 'plugins\\sergeikuznetsov\\juniortestplugin\\controllers\\products.php',
  'SergeiKuznetsov\\JuniorTestPlugin\\Models\\Product' => 'plugins\\sergeikuznetsov\\juniortestplugin\\models\\Product.php',
  'SergeiKuznetsov\\JuniorTestPlugin\\Models\\Category' => 'plugins\\sergeikuznetsov\\juniortestplugin\\models\\Category.php',
  'sergeikuznetsov\\juniortestplugin\\Controllers\\categories' => 'plugins\\sergeikuznetsov\\juniortestplugin\\controllers\\categories.php',
  'SergeiKuznetsov\\JuniorTestPlugin\\Controllers\\Categories' => 'plugins\\sergeikuznetsov\\juniortestplugin\\controllers\\Categories.php',
  'SergeiKuznetsov\\JuniorTestPlugin\\Classes\\Resources\\ProductResource' => 'plugins\\sergeikuznetsov\\juniortestplugin\\classes\\resources\\ProductResource.php',
  'SergeiKuznetsov\\JuniorTestPlugin\\Classes\\Resources\\CategoryResource' => 'plugins\\sergeikuznetsov\\juniortestplugin\\classes\\resources\\CategoryResource.php',
  'backend\\Controllers\\media' => 'modules\\backend\\controllers\\media.php',
  'cms\\Controllers\\index' => 'modules\\cms\\controllers\\index.php',
);